# Generated by Django 4.0.4 on 2022-07-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_cliente_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='codigo',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
