# Generated by Django 4.0.4 on 2022-07-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_rename_codigo_accesorio_id_remove_accesorio_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='precio',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
