# Generated by Django 4.0.4 on 2022-07-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_alter_accesorio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
